name = "Vanilla Supreme Commander - Balance Mod"
uid = "77644f48-4161-465b-968c-7c192e33de21"
version = 2
copyright = "speed2 - Everyone caught stealing my superior code will get banished from time and space. FOREVER."
description = "Brings the unit balance from the original Supreme Commander game."
icon = "/mods/Vanilla/vanilla_icon.png"
author = "speed2"
selectable = true
enabled = true
exclusive = false
ui_only = false