name = "Vanilla Supreme Commander - Balance Mod"
uid = "bb44e386-bc6d-4038-857d-5f3792a67eb0"
version = 3
copyright = "speed2 - Everyone caught stealing my superior code will get banished from time and space. FOREVER."
description = "Brings the unit balance from the original Supreme Commander game."
icon = "/mods/Vanilla/vanilla_icon.png"
author = "speed2"
selectable = true
enabled = true
exclusive = false
ui_only = false